CONFIG_KEYS = {
    "NEXTUP_RECOMMENDATIONS_DIR": 'NEXTUP_RECOMMENDATIONS_DIR',
    "GENERATE_RECOS_FOR": "GENERATE_RECOS_FOR",
    "MIN_MOVIE_WATCH_PERCENT": "MIN_MOVIE_WATCH_PERCENT",
    "MAX_MOVIE_DAYS_LOOKBACK": "MAX_MOVIE_DAYS_LOOKBACK",
    "MAX_RECOMMENDATIONS_PER_MOVIE": "MAX_RECOMMENDATIONS_PER_MOVIE",
    "MOVIE_LIBRARY_IDS": "MOVIE_LIBRARY_IDS",
    "SERIES_LIBRARY_IDS": "SERIES_LIBRARY_IDS",
    "MAX_SERIES_DAYS_LOOKBACK": "MAX_SERIES_DAYS_LOOKBACK",
    "MAX_RECOMMENDATIONS_PER_SERIES": "MAX_RECOMMENDATIONS_PER_SERIES",
    "DISABLE_MOVIE_RECOMMENDATIONS": "DISABLE_MOVIE_RECOMMENDATIONS",
    "DISABLE_SERIES_RECOMMENDATIONS": "DISABLE_SERIES_RECOMMENDATIONS",
    "RECOMMENDATIONS_CRON_SCHEDULE": "RECOMMENDATIONS_CRON_SCHEDULE",
    "PLACEHOLDER_FILE_PATH": "PLACEHOLDER_FILE_PATH",
    "TZ": "TZ"
}