CONFIG_KEYS = {
    "NEXTUP_RECOMMENDATIONS_DIR": 'NEXTUP_RECOMMENDATIONS_DIR',
    "GENERATE_RECOS_FOR": "GENERATE_RECOS_FOR",

    "DISABLE_MOVIE_RECOMMENDATIONS": "DISABLE_MOVIE_RECOMMENDATIONS",
    "MOVIE_LIBRARY_IDS": "MOVIE_LIBRARY_IDS",
    "MIN_MOVIE_WATCH_PERCENT": "MIN_MOVIE_WATCH_PERCENT",
    "MAX_MOVIE_DAYS_LOOKBACK": "MAX_MOVIE_DAYS_LOOKBACK",
    "MAX_RECOMMENDATIONS_PER_MOVIE": "MAX_RECOMMENDATIONS_PER_MOVIE",
    "MAX_TOTAL_MOVIE_RECOMMENDATIONS": "MAX_TOTAL_MOVIE_RECOMMENDATIONS",
    "INCLUDE_UPCOMING_MOVIE_RECOMMENDATIONS": 'INCLUDE_UPCOMING_MOVIE_RECOMMENDATIONS',
    "INCLUDE_POPULAR_MOVIE_RECOMMENDATIONS": 'INCLUDE_POPULAR_MOVIE_RECOMMENDATIONS',
    "POPULAR_MOVIES_COUNT": "POPULAR_MOVIES_COUNT",
    "UPCOMING_MOVIES_COUNT": "UPCOMING_MOVIES_COUNT",

    "DISABLE_SERIES_RECOMMENDATIONS": "DISABLE_SERIES_RECOMMENDATIONS",
    "SERIES_LIBRARY_IDS": "SERIES_LIBRARY_IDS",
    "MAX_SERIES_DAYS_LOOKBACK": "MAX_SERIES_DAYS_LOOKBACK",
    "MAX_RECOMMENDATIONS_PER_SERIES": "MAX_RECOMMENDATIONS_PER_SERIES",
    "MIN_EPISODE_WATCH_COUNT": "MIN_EPISODE_WATCH_COUNT",
    "MAX_TOTAL_SERIES_RECOMMENDATIONS": "MAX_TOTAL_SERIES_RECOMMENDATIONS",
    "INCLUDE_POPULAR_SERIES_RECOMMENDATIONS": "INCLUDE_POPULAR_SERIES_RECOMMENDATIONS",
    "POPULAR_SERIES_COUNT": "POPULAR_SERIES_COUNT",

    "RECOMMENDATIONS_CRON_SCHEDULE": "RECOMMENDATIONS_CRON_SCHEDULE",
    "PLACEHOLDER_FILE_PATH": "PLACEHOLDER_FILE_PATH",
    "TZ": "TZ"
}