JELLYFIN_SECRET_KEYS = {
    "JELLYFIN_API_KEY": 'JELLYFIN_API_KEY',
    "JELLYFIN_URL": 'JELLYFIN_URL',
    "JELLYFIN_USERS": 'JELLYFIN_USERS'
}

WEBHOOK_NOTIFICATION_TYPES = {
    "USER_DATA_SAVED": "UserDataSaved"
}

SUPPORTED_WEBHOOK_NOTIFICATION_TYPES = [
    WEBHOOK_NOTIFICATION_TYPES["USER_DATA_SAVED"]
]