WATCHSTATE_SECRET_KEYS = {
    "WATCHSTATE_USERNAME": 'WATCHSTATE_USERNAME',
    "WATCHSTATE_PASSWORD": 'WATCHSTATE_PASSWORD',
    "WATCHSTATE_URL": 'WATCHSTATE_URL',
    "WATCHSTATE_MAIN_USER_TO_JELLYFIN_MAP": 'WATCHSTATE_MAIN_USER_TO_JELLYFIN_MAP'
}