# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/sct/overseerr/develop/overseerr-api.yml
#   timestamp: 2026-03-22T16:04:53+00:00

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired


class User(TypedDict):
    id: int
    email: str
    username: NotRequired[str]
    plexToken: NotRequired[str]
    plexUsername: NotRequired[str]
    userType: NotRequired[int]
    permissions: NotRequired[float]
    avatar: NotRequired[str]
    createdAt: str
    updatedAt: str
    requestCount: NotRequired[float]


class UserSettings(TypedDict):
    locale: NotRequired[str]
    region: NotRequired[str]
    originalLanguage: NotRequired[str]


class MainSettings(TypedDict):
    apiKey: NotRequired[str]
    appLanguage: NotRequired[str]
    applicationTitle: NotRequired[str]
    applicationUrl: NotRequired[str]
    trustProxy: NotRequired[bool]
    csrfProtection: NotRequired[bool]
    hideAvailable: NotRequired[bool]
    partialRequestsEnabled: NotRequired[bool]
    localLogin: NotRequired[bool]
    newPlexLogin: NotRequired[bool]
    defaultPermissions: NotRequired[float]


class PlexLibrary(TypedDict):
    id: str
    name: str
    enabled: bool


class PlexSettings(TypedDict):
    name: str
    machineId: str
    ip: str
    port: float
    useSsl: NotRequired[bool]
    libraries: NotRequired[list[PlexLibrary]]
    webAppUrl: NotRequired[str]


class PlexConnection(TypedDict):
    protocol: str
    address: str
    port: float
    uri: str
    local: bool
    status: NotRequired[float]
    message: NotRequired[str]


class PlexDevice(TypedDict):
    name: str
    product: str
    productVersion: str
    platform: str
    platformVersion: NotRequired[str]
    device: str
    clientIdentifier: str
    createdAt: str
    lastSeenAt: str
    provides: list[str]
    owned: bool
    ownerID: NotRequired[str]
    home: NotRequired[bool]
    sourceTitle: NotRequired[str]
    accessToken: NotRequired[str]
    publicAddress: NotRequired[str]
    httpsRequired: NotRequired[bool]
    synced: NotRequired[bool]
    relay: NotRequired[bool]
    dnsRebindingProtection: NotRequired[bool]
    natLoopbackSupported: NotRequired[bool]
    publicAddressMatches: NotRequired[bool]
    presence: NotRequired[bool]
    connection: list[PlexConnection]


class TautulliSettings(TypedDict):
    hostname: NotRequired[str]
    port: NotRequired[float]
    useSsl: NotRequired[bool]
    apiKey: NotRequired[str]
    externalUrl: NotRequired[str]


class RadarrSettings(TypedDict):
    id: NotRequired[float]
    name: str
    hostname: str
    port: float
    apiKey: str
    useSsl: bool
    baseUrl: NotRequired[str]
    activeProfileId: float
    activeProfileName: str
    activeDirectory: str
    is4k: bool
    minimumAvailability: str
    isDefault: bool
    externalUrl: NotRequired[str]
    syncEnabled: NotRequired[bool]
    preventSearch: NotRequired[bool]


class SonarrSettings(TypedDict):
    id: NotRequired[float]
    name: str
    hostname: str
    port: float
    apiKey: str
    useSsl: bool
    baseUrl: NotRequired[str]
    activeProfileId: float
    activeProfileName: str
    activeDirectory: str
    activeLanguageProfileId: NotRequired[float]
    activeAnimeProfileId: NotRequired[float]
    activeAnimeLanguageProfileId: NotRequired[float]
    activeAnimeProfileName: NotRequired[str]
    activeAnimeDirectory: NotRequired[str]
    is4k: bool
    enableSeasonFolders: bool
    isDefault: bool
    externalUrl: NotRequired[str]
    syncEnabled: NotRequired[bool]
    preventSearch: NotRequired[bool]


class ServarrTag(TypedDict):
    id: NotRequired[float]
    label: NotRequired[str]


class PublicSettings(TypedDict):
    initialized: NotRequired[bool]


class Genre(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]


class Company(TypedDict):
    id: NotRequired[float]
    logo_path: NotRequired[str]
    name: NotRequired[str]


class ProductionCompany(TypedDict):
    id: NotRequired[float]
    logoPath: NotRequired[str]
    originCountry: NotRequired[str]
    name: NotRequired[str]


class Network(TypedDict):
    id: NotRequired[float]
    logoPath: NotRequired[str]
    originCountry: NotRequired[str]
    name: NotRequired[str]


class RelatedVideo(TypedDict):
    url: NotRequired[str]
    key: NotRequired[str]
    name: NotRequired[str]
    size: NotRequired[float]
    type: NotRequired[
        Literal[
            'Clip',
            'Teaser',
            'Trailer',
            'Featurette',
            'Opening Credits',
            'Behind the Scenes',
            'Bloopers',
        ]
    ]
    site: NotRequired[Literal['YouTube']]


class ProductionCountry(TypedDict):
    iso_3166_1: NotRequired[str]
    name: NotRequired[str]


class ReleaseDate(TypedDict):
    certification: NotRequired[str]
    iso_639_1: NotRequired[str]
    note: NotRequired[str]
    release_date: NotRequired[str]
    type: NotRequired[float]


class Result(TypedDict):
    iso_3166_1: NotRequired[str]
    rating: NotRequired[str]
    release_dates: NotRequired[list[ReleaseDate]]


class Releases(TypedDict):
    results: NotRequired[list[Result]]


class Collection(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]
    posterPath: NotRequired[str]
    backdropPath: NotRequired[str]


class Episode(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]
    airDate: NotRequired[str]
    episodeNumber: NotRequired[float]
    overview: NotRequired[str]
    productionCode: NotRequired[str]
    seasonNumber: NotRequired[float]
    showId: NotRequired[float]
    stillPath: NotRequired[str]
    voteAverage: NotRequired[float]
    voteCount: NotRequired[float]


class Season(TypedDict):
    id: NotRequired[float]
    airDate: NotRequired[str]
    episodeCount: NotRequired[float]
    name: NotRequired[str]
    overview: NotRequired[str]
    posterPath: NotRequired[str]
    seasonNumber: NotRequired[float]
    episodes: NotRequired[list[Episode]]


class Result1(TypedDict):
    iso_3166_1: NotRequired[str]
    rating: NotRequired[str]


class ContentRatings(TypedDict):
    results: NotRequired[list[Result1]]


class CreatedByItem(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]
    gender: NotRequired[float]
    profilePath: NotRequired[str]


class Cast(TypedDict):
    id: NotRequired[float]
    castId: NotRequired[float]
    character: NotRequired[str]
    creditId: NotRequired[str]
    gender: NotRequired[float]
    name: NotRequired[str]
    order: NotRequired[float]
    profilePath: NotRequired[str]


class Crew(TypedDict):
    id: NotRequired[float]
    creditId: NotRequired[str]
    gender: NotRequired[float]
    name: NotRequired[str]
    job: NotRequired[str]
    department: NotRequired[str]
    profilePath: NotRequired[str]


class ExternalIds(TypedDict):
    facebookId: NotRequired[str]
    freebaseId: NotRequired[str]
    freebaseMid: NotRequired[str]
    imdbId: NotRequired[str]
    instagramId: NotRequired[str]
    tvdbId: NotRequired[float]
    tvrageId: NotRequired[float]
    twitterId: NotRequired[str]


class ServiceProfile(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]


class PageInfo(TypedDict):
    page: NotRequired[float]
    pages: NotRequired[float]
    results: NotRequired[float]


class Options(TypedDict):
    botUsername: NotRequired[str]
    botAvatarUrl: NotRequired[str]
    webhookUrl: NotRequired[str]
    enableMentions: NotRequired[bool]


class DiscordSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options]


class Options1(TypedDict):
    webhookUrl: NotRequired[str]


class SlackSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options1]


class WebPushSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]


class Options2(TypedDict):
    webhookUrl: NotRequired[str]
    authHeader: NotRequired[str]
    jsonPayload: NotRequired[str]


class WebhookSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options2]


class Options3(TypedDict):
    botUsername: NotRequired[str]
    botAPI: NotRequired[str]
    chatId: NotRequired[str]
    sendSilently: NotRequired[bool]


class TelegramSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options3]


class Options4(TypedDict):
    accessToken: NotRequired[str]
    channelTag: NotRequired[str]


class PushbulletSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options4]


class Options5(TypedDict):
    accessToken: NotRequired[str]
    userToken: NotRequired[str]
    sound: NotRequired[str]


class PushoverSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options5]


class Options6(TypedDict):
    url: NotRequired[str]
    token: NotRequired[str]


class GotifySettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options6]


class Options7(TypedDict):
    webhookUrl: NotRequired[str]
    profileName: NotRequired[str]


class LunaSeaSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options7]


class Options8(TypedDict):
    emailFrom: NotRequired[str]
    senderName: NotRequired[str]
    smtpHost: NotRequired[str]
    smtpPort: NotRequired[float]
    secure: NotRequired[bool]
    ignoreTls: NotRequired[bool]
    requireTls: NotRequired[bool]
    authUser: NotRequired[str]
    authPass: NotRequired[str]
    allowSelfSigned: NotRequired[bool]


class NotificationEmailSettings(TypedDict):
    enabled: NotRequired[bool]
    types: NotRequired[float]
    options: NotRequired[Options8]


class Job(TypedDict):
    id: NotRequired[str]
    type: NotRequired[Literal['process', 'command']]
    interval: NotRequired[Literal['short', 'long', 'fixed']]
    name: NotRequired[str]
    nextExecutionTime: NotRequired[str]
    running: NotRequired[bool]


class PersonDetails(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]
    deathday: NotRequired[str]
    knownForDepartment: NotRequired[str]
    alsoKnownAs: NotRequired[list[str]]
    gender: NotRequired[str]
    biography: NotRequired[str]
    popularity: NotRequired[str]
    placeOfBirth: NotRequired[str]
    profilePath: NotRequired[str]
    adult: NotRequired[bool]
    imdbId: NotRequired[str]
    homepage: NotRequired[str]


class Keyword(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]


class SpokenLanguage(TypedDict):
    englishName: NotRequired[str]
    iso_639_1: NotRequired[str]
    name: NotRequired[str]


class Image(TypedDict):
    coverType: NotRequired[str]
    url: NotRequired[str]


class Season1(TypedDict):
    seasonNumber: NotRequired[float]
    monitored: NotRequired[bool]


class Rating(TypedDict):
    votes: NotRequired[float]
    value: NotRequired[float]


class AddOption(TypedDict):
    ignoreEpisodesWithFiles: NotRequired[bool]
    ignoreEpisodesWithoutFiles: NotRequired[bool]
    searchForMissingEpisodes: NotRequired[bool]


class SonarrSeries(TypedDict):
    title: NotRequired[str]
    sortTitle: NotRequired[str]
    seasonCount: NotRequired[float]
    status: NotRequired[str]
    overview: NotRequired[str]
    network: NotRequired[str]
    airTime: NotRequired[str]
    images: NotRequired[list[Image]]
    remotePoster: NotRequired[str]
    seasons: NotRequired[list[Season1]]
    year: NotRequired[float]
    path: NotRequired[str]
    profileId: NotRequired[float]
    languageProfileId: NotRequired[float]
    seasonFolder: NotRequired[bool]
    monitored: NotRequired[bool]
    useSceneNumbering: NotRequired[bool]
    runtime: NotRequired[float]
    tvdbId: NotRequired[float]
    tvRageId: NotRequired[float]
    tvMazeId: NotRequired[float]
    firstAired: NotRequired[str]
    lastInfoSync: NotRequired[str]
    seriesType: NotRequired[str]
    cleanTitle: NotRequired[str]
    imdbId: NotRequired[str]
    titleSlug: NotRequired[str]
    certification: NotRequired[str]
    genres: NotRequired[list[str]]
    tags: NotRequired[list[str]]
    added: NotRequired[str]
    ratings: NotRequired[list[Rating]]
    qualityProfileId: NotRequired[float]
    id: NotRequired[float]
    rootFolderPath: NotRequired[str]
    addOptions: NotRequired[list[AddOption]]


class NotificationAgentTypes(TypedDict):
    discord: NotRequired[float]
    email: NotRequired[float]
    pushbullet: NotRequired[float]
    pushover: NotRequired[float]
    slack: NotRequired[float]
    telegram: NotRequired[float]
    webhook: NotRequired[float]
    webpush: NotRequired[float]


class WatchProviderDetails(TypedDict):
    displayPriority: NotRequired[float]
    logoPath: NotRequired[str]
    id: NotRequired[float]
    name: NotRequired[str]


class IssueComment(TypedDict):
    id: NotRequired[float]
    user: NotRequired[User]
    message: NotRequired[str]


class DiscoverSlider(TypedDict):
    id: NotRequired[float]
    type: float
    title: str
    isBuiltIn: NotRequired[bool]
    enabled: bool
    data: str


class WatchProviderRegion(TypedDict):
    iso_3166_1: NotRequired[str]
    english_name: NotRequired[str]
    native_name: NotRequired[str]


class Credits(TypedDict):
    cast: NotRequired[list[Cast]]
    crew: NotRequired[list[Crew]]


class UserSettingsNotifications(TypedDict):
    notificationTypes: NotRequired[NotificationAgentTypes]
    emailEnabled: NotRequired[bool]
    pgpKey: NotRequired[str]
    discordEnabled: NotRequired[bool]
    discordEnabledTypes: NotRequired[float]
    discordId: NotRequired[str]
    pushbulletAccessToken: NotRequired[str]
    pushoverApplicationToken: NotRequired[str]
    pushoverUserKey: NotRequired[str]
    pushoverSound: NotRequired[str]
    telegramEnabled: NotRequired[bool]
    telegramBotUsername: NotRequired[str]
    telegramChatId: NotRequired[str]
    telegramSendSilently: NotRequired[bool]


class WatchProvider(TypedDict):
    iso_3166_1: NotRequired[str]
    link: NotRequired[str]
    buy: NotRequired[list[WatchProviderDetails]]
    flatrate: NotRequired[list[WatchProviderDetails]]


WatchProviders: TypeAlias = list[WatchProvider]


class MovieResult(TypedDict):
    id: float
    mediaType: str
    popularity: NotRequired[float]
    posterPath: NotRequired[str]
    backdropPath: NotRequired[str]
    voteCount: NotRequired[float]
    voteAverage: NotRequired[float]
    genreIds: NotRequired[list[float]]
    overview: NotRequired[str]
    originalLanguage: NotRequired[str]
    title: str
    originalTitle: NotRequired[str]
    releaseDate: NotRequired[str]
    adult: NotRequired[bool]
    video: NotRequired[bool]
    mediaInfo: NotRequired[MediaInfo]


class TvResult(TypedDict):
    id: NotRequired[float]
    mediaType: NotRequired[str]
    popularity: NotRequired[float]
    posterPath: NotRequired[str]
    backdropPath: NotRequired[str]
    voteCount: NotRequired[float]
    voteAverage: NotRequired[float]
    genreIds: NotRequired[list[float]]
    overview: NotRequired[str]
    originalLanguage: NotRequired[str]
    name: NotRequired[str]
    originalName: NotRequired[str]
    originCountry: NotRequired[list[str]]
    firstAirDate: NotRequired[str]
    mediaInfo: NotRequired[MediaInfo]


class PersonResult(TypedDict):
    id: NotRequired[float]
    profilePath: NotRequired[str]
    adult: NotRequired[bool]
    mediaType: NotRequired[str]
    knownFor: NotRequired[list[MovieResult | TvResult]]


class MovieDetails(TypedDict):
    id: NotRequired[float]
    imdbId: NotRequired[str]
    adult: NotRequired[bool]
    backdropPath: NotRequired[str]
    posterPath: NotRequired[str]
    budget: NotRequired[float]
    genres: NotRequired[list[Genre]]
    homepage: NotRequired[str]
    relatedVideos: NotRequired[list[RelatedVideo]]
    originalLanguage: NotRequired[str]
    originalTitle: NotRequired[str]
    overview: NotRequired[str]
    popularity: NotRequired[float]
    productionCompanies: NotRequired[list[ProductionCompany]]
    productionCountries: NotRequired[list[ProductionCountry]]
    releaseDate: NotRequired[str]
    releases: NotRequired[Releases]
    revenue: NotRequired[float]
    runtime: NotRequired[float]
    spokenLanguages: NotRequired[list[SpokenLanguage]]
    status: NotRequired[str]
    tagline: NotRequired[str]
    title: NotRequired[str]
    video: NotRequired[bool]
    voteAverage: NotRequired[float]
    voteCount: NotRequired[float]
    credits: NotRequired[Credits]
    collection: NotRequired[Collection]
    externalIds: NotRequired[ExternalIds]
    mediaInfo: NotRequired[MediaInfo]
    watchProviders: NotRequired[list[WatchProviders]]


class TvDetails(TypedDict):
    id: NotRequired[float]
    backdropPath: NotRequired[str]
    posterPath: NotRequired[str]
    contentRatings: NotRequired[ContentRatings]
    createdBy: NotRequired[list[CreatedByItem]]
    episodeRunTime: NotRequired[list[float]]
    firstAirDate: NotRequired[str]
    genres: NotRequired[list[Genre]]
    homepage: NotRequired[str]
    inProduction: NotRequired[bool]
    languages: NotRequired[list[str]]
    lastAirDate: NotRequired[str]
    lastEpisodeToAir: NotRequired[Episode]
    name: NotRequired[str]
    nextEpisodeToAir: NotRequired[Episode]
    networks: NotRequired[list[ProductionCompany]]
    numberOfEpisodes: NotRequired[float]
    numberOfSeason: NotRequired[float]
    originCountry: NotRequired[list[str]]
    originalLanguage: NotRequired[str]
    originalName: NotRequired[str]
    overview: NotRequired[str]
    popularity: NotRequired[float]
    productionCompanies: NotRequired[list[ProductionCompany]]
    productionCountries: NotRequired[list[ProductionCountry]]
    spokenLanguages: NotRequired[list[SpokenLanguage]]
    seasons: NotRequired[list[Season]]
    status: NotRequired[str]
    tagline: NotRequired[str]
    type: NotRequired[str]
    voteAverage: NotRequired[float]
    voteCount: NotRequired[float]
    credits: NotRequired[Credits]
    externalIds: NotRequired[ExternalIds]
    keywords: NotRequired[list[Keyword]]
    mediaInfo: NotRequired[MediaInfo]
    watchProviders: NotRequired[list[WatchProviders]]


class MediaRequest(TypedDict):
    id: float
    status: float
    media: NotRequired[MediaInfo]
    createdAt: NotRequired[str]
    updatedAt: NotRequired[str]
    requestedBy: NotRequired[User]
    modifiedBy: NotRequired[User | str]
    is4k: NotRequired[bool]
    serverId: NotRequired[float]
    profileId: NotRequired[float]
    rootFolder: NotRequired[str]


class MediaInfo(TypedDict):
    id: NotRequired[float]
    tmdbId: NotRequired[float]
    tvdbId: NotRequired[float]
    status: NotRequired[float]
    requests: NotRequired[list[MediaRequest]]
    createdAt: NotRequired[str]
    updatedAt: NotRequired[str]


class CreditCast(TypedDict):
    id: NotRequired[float]
    originalLanguage: NotRequired[str]
    episodeCount: NotRequired[float]
    overview: NotRequired[str]
    originCountry: NotRequired[list[str]]
    originalName: NotRequired[str]
    voteCount: NotRequired[float]
    name: NotRequired[str]
    mediaType: NotRequired[str]
    popularity: NotRequired[float]
    creditId: NotRequired[str]
    backdropPath: NotRequired[str]
    firstAirDate: NotRequired[str]
    voteAverage: NotRequired[float]
    genreIds: NotRequired[list[float]]
    posterPath: NotRequired[str]
    originalTitle: NotRequired[str]
    video: NotRequired[bool]
    title: NotRequired[str]
    adult: NotRequired[bool]
    releaseDate: NotRequired[str]
    character: NotRequired[str]
    mediaInfo: NotRequired[MediaInfo]


class CreditCrew(TypedDict):
    id: NotRequired[float]
    originalLanguage: NotRequired[str]
    episodeCount: NotRequired[float]
    overview: NotRequired[str]
    originCountry: NotRequired[list[str]]
    originalName: NotRequired[str]
    voteCount: NotRequired[float]
    name: NotRequired[str]
    mediaType: NotRequired[str]
    popularity: NotRequired[float]
    creditId: NotRequired[str]
    backdropPath: NotRequired[str]
    firstAirDate: NotRequired[str]
    voteAverage: NotRequired[float]
    genreIds: NotRequired[list[float]]
    posterPath: NotRequired[str]
    originalTitle: NotRequired[str]
    video: NotRequired[bool]
    title: NotRequired[str]
    adult: NotRequired[bool]
    releaseDate: NotRequired[str]
    department: NotRequired[str]
    job: NotRequired[str]
    mediaInfo: NotRequired[MediaInfo]


class Collection1(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]
    overview: NotRequired[str]
    posterPath: NotRequired[str]
    backdropPath: NotRequired[str]
    parts: NotRequired[list[MovieResult]]


class Issue(TypedDict):
    id: NotRequired[float]
    issueType: NotRequired[float]
    media: NotRequired[MediaInfo]
    createdBy: NotRequired[User]
    modifiedBy: NotRequired[User]
    comments: NotRequired[list[IssueComment]]
